sudo: required
services:
    - docker
before_install:
    - docker build -t meh/docker-react -f Dockerfile.dev .
script:
    - docker run  meh/docker-react 
deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-692667656448"
    bucket_path: "my-docker-react"
on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
    secure: "$AWS_SECRET_KEY"